language: python
python:
  - "2.7"

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-phpdomain
  - pip install git+https://github.com/marc1706/sphinx-php.git

script:
  - cd development
  - make html

branches:
  only:
    - master
    - /^\d+(\.\d+)?\.x$/

sudo: false
